spring:
  datasource:
    url: jdbc:mysql://121.199.70.188:3306/spring_cache
    username: root
    password: 123456
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      kun:
        cache:
          mapper: debug